import type {
  Audit,
  AuditTemplate,
  Branch,
  Company,
  CorrectiveAction,
  Employee,
  AppNotification,
  RoleDefinition,
} from "./types"

/**
 * Mock data layer.
 *
 * Everything the UI renders comes from these exports. To integrate a real
 * backend, replace each export with an async data fetch (Supabase query / API
 * route) that returns the same shape — the components won't need to change.
 */

export const companies: Company[] = [
  {
    id: "c1",
    name: "Nomad Coffee",
    logoText: "NC",
    industry: "Maqaayado & Kafitariyo",
    branchCount: 12,
    employeeCount: 148,
    avgScore: 91,
    createdAt: "2024-02-10",
  },
  {
    id: "c2",
    name: "Banaadir Mart",
    logoText: "BM",
    industry: "Suuqyo (Retail)",
    branchCount: 8,
    employeeCount: 96,
    avgScore: 84,
    createdAt: "2024-05-22",
  },
  {
    id: "c3",
    name: "Shifo Pharmacy",
    logoText: "SP",
    industry: "Caafimaad",
    branchCount: 5,
    employeeCount: 41,
    avgScore: 96,
    createdAt: "2024-08-01",
  },
  {
    id: "c4",
    name: "Xamar Bakery",
    logoText: "XB",
    industry: "Rooti & Cunto",
    branchCount: 6,
    employeeCount: 63,
    avgScore: 78,
    createdAt: "2025-01-14",
  },
]

export const branches: Branch[] = [
  {
    id: "b1",
    companyId: "c1",
    name: "Nomad Coffee — Makka Al-Mukarama",
    city: "Muqdisho",
    address: "Makka Al-Mukarama Rd",
    manager: "Faadumo Cali",
    employeeCount: 14,
    lastAuditScore: 93,
    lastAuditAt: "2026-08-12",
    status: "active",
  },
  {
    id: "b2",
    companyId: "c1",
    name: "Nomad Coffee — Taleex",
    city: "Muqdisho",
    address: "Taleex St",
    manager: "Yuusuf Warsame",
    employeeCount: 11,
    lastAuditScore: 88,
    lastAuditAt: "2026-08-09",
    status: "active",
  },
  {
    id: "b3",
    companyId: "c2",
    name: "Banaadir Mart — Bakaaraha",
    city: "Muqdisho",
    address: "Bakaaraha Market",
    manager: "Xasan Cabdi",
    employeeCount: 18,
    lastAuditScore: 81,
    lastAuditAt: "2026-08-05",
    status: "active",
  },
  {
    id: "b4",
    companyId: "c3",
    name: "Shifo Pharmacy — Hodan",
    city: "Muqdisho",
    address: "Hodan District",
    manager: "Caasho Maxamed",
    employeeCount: 9,
    lastAuditScore: 97,
    lastAuditAt: "2026-08-14",
    status: "active",
  },
  {
    id: "b5",
    companyId: "c4",
    name: "Xamar Bakery — Wadajir",
    city: "Muqdisho",
    address: "Wadajir District",
    manager: "Cabdiraxmaan Nuur",
    employeeCount: 12,
    lastAuditScore: 74,
    lastAuditAt: "2026-08-02",
    status: "active",
  },
  {
    id: "b6",
    companyId: "c1",
    name: "Nomad Coffee — Kismaayo",
    city: "Kismaayo",
    address: "Central Kismaayo",
    manager: "Maryan Ismaaciil",
    employeeCount: 10,
    lastAuditScore: null,
    lastAuditAt: null,
    status: "active",
  },
]

export const employees: Employee[] = [
  {
    id: "e1",
    name: "Faadumo Cali",
    email: "faadumo@nomadcoffee.so",
    phone: "+252 61 111 2222",
    role: "manager",
    branchId: "b1",
    branchName: "Nomad Coffee — Makka Al-Mukarama",
    active: true,
    avatarText: "FC",
    joinedAt: "2024-03-01",
  },
  {
    id: "e2",
    name: "Yuusuf Warsame",
    email: "yuusuf@nomadcoffee.so",
    phone: "+252 61 222 3333",
    role: "manager",
    branchId: "b2",
    branchName: "Nomad Coffee — Taleex",
    active: true,
    avatarText: "YW",
    joinedAt: "2024-04-11",
  },
  {
    id: "e3",
    name: "Caasho Maxamed",
    email: "caasho@shifopharma.so",
    phone: "+252 61 333 4444",
    role: "auditor",
    branchId: "b4",
    branchName: "Shifo Pharmacy — Hodan",
    active: true,
    avatarText: "CM",
    joinedAt: "2024-09-05",
  },
  {
    id: "e4",
    name: "Cabdiraxmaan Nuur",
    email: "cabdiraxmaan@xamarbakery.so",
    phone: "+252 61 444 5555",
    role: "auditor",
    branchId: "b5",
    branchName: "Xamar Bakery — Wadajir",
    active: true,
    avatarText: "CN",
    joinedAt: "2025-01-20",
  },
  {
    id: "e5",
    name: "Maryan Ismaaciil",
    email: "maryan@nomadcoffee.so",
    phone: "+252 61 555 6666",
    role: "owner",
    branchId: null,
    branchName: null,
    active: true,
    avatarText: "MI",
    joinedAt: "2024-02-10",
  },
  {
    id: "e6",
    name: "Xasan Cabdi",
    email: "xasan@banaadirmart.so",
    phone: "+252 61 666 7777",
    role: "viewer",
    branchId: "b3",
    branchName: "Banaadir Mart — Bakaaraha",
    active: false,
    avatarText: "XC",
    joinedAt: "2024-06-30",
  },
]

export const roles: RoleDefinition[] = [
  {
    key: "owner",
    labelSo: "Milkiile / Franchisor",
    labelEn: "Owner",
    description: "Gelitaan buuxa: dhammaan shirkadaha, laamaha, warbixinnada iyo dejinta.",
    permissions: ["Maamul dhammaan", "Abuur templates", "Arag warbixinno", "Maamul isticmaaleyaal", "Lacag & jID"],
    userCount: 3,
  },
  {
    key: "manager",
    labelSo: "Maamule Laan",
    labelEn: "Manager",
    description: "Maamula laan gaar ah: shaqaalaha, baaritaannada iyo talaabooyinka saxidda.",
    permissions: ["Arag laantiisa", "Bilow baaritaan", "U qoondee talaabo sax", "Arag warbixin laan"],
    userCount: 12,
  },
  {
    key: "auditor",
    labelSo: "Baare / Kormeere",
    labelEn: "Auditor",
    description: "Fuliya baaritaannada goobta, sawiro iyo jawaabo pass/fail.",
    permissions: ["Fuli baaritaan", "Sawir caddayn", "Qor faallo", "Gudbi baaritaan"],
    userCount: 34,
  },
  {
    key: "viewer",
    labelSo: "Daawade",
    labelEn: "Viewer",
    description: "Kaliya arag warbixinnada iyo natiijooyinka; wax bedeli karo majiro.",
    permissions: ["Arag warbixin", "Soo dejiso PDF"],
    userCount: 8,
  },
]

export const templates: AuditTemplate[] = [
  {
    id: "t1",
    name: "Nadaafadda & Badbaadada Cuntada",
    category: "Maqaayad",
    description: "Kormeer nadaafad, kayd cunto iyo badbaadada shaqaalaha ee maqaayadaha.",
    questionCount: 24,
    usageCount: 186,
    updatedAt: "2026-08-10",
    published: true,
    sections: [
      {
        id: "s1",
        title: "Nadaafadda Guud",
        questions: [
          {
            id: "q1",
            text: "Sagxadaha iyo miisaska ma nadiif baa?",
            type: "pass_fail_na",
            weight: 2,
            requirePhotoOnFail: true,
            requireNoteOnFail: true,
          },
          {
            id: "q2",
            text: "Musqulaha ma leeyihiin saabuun iyo biyo?",
            type: "pass_fail_na",
            weight: 3,
            requirePhotoOnFail: true,
            requireNoteOnFail: false,
          },
          {
            id: "q3",
            text: "Heerkulka qaboojiyaha (°C)",
            type: "number",
            weight: 1,
            requirePhotoOnFail: false,
            requireNoteOnFail: false,
          },
        ],
      },
      {
        id: "s2",
        title: "Kaydka Cuntada",
        questions: [
          {
            id: "q4",
            text: "Cuntada ma leedahay taariikh dhicis (expiry) cad?",
            type: "pass_fail_na",
            weight: 3,
            requirePhotoOnFail: true,
            requireNoteOnFail: true,
          },
          {
            id: "q5",
            text: "Ma jiraan cunto la kala saaray (raw/cooked)?",
            type: "pass_fail_na",
            weight: 2,
            requirePhotoOnFail: false,
            requireNoteOnFail: false,
          },
        ],
      },
    ],
  },
  {
    id: "t2",
    name: "Adeegga Macaamiisha",
    category: "Retail",
    description: "Qiimaynta tayada adeegga, muuqaalka bakhaarka iyo diyaarnimada shaqaalaha.",
    questionCount: 16,
    usageCount: 92,
    updatedAt: "2026-08-06",
    published: true,
    sections: [
      {
        id: "s3",
        title: "Soo dhaweynta Macaamiisha",
        questions: [
          {
            id: "q6",
            text: "Shaqaalaha ma soo dhaweeyaan macaamiisha 30 sekan gudahood?",
            type: "pass_fail_na",
            weight: 2,
            requirePhotoOnFail: false,
            requireNoteOnFail: true,
          },
        ],
      },
    ],
  },
  {
    id: "t3",
    name: "Badbaadada Caafimaad (Farmashiye)",
    category: "Caafimaad",
    description: "Hubinta kaydinta dawooyinka, taariikhaha dhicitaanka iyo diiwaanka.",
    questionCount: 20,
    usageCount: 54,
    updatedAt: "2026-07-28",
    published: false,
    sections: [
      {
        id: "s4",
        title: "Kaydinta Dawooyinka",
        questions: [
          {
            id: "q7",
            text: "Dawooyinka ma lagu kaydiyaa heerkul saxda ah?",
            type: "pass_fail_na",
            weight: 3,
            requirePhotoOnFail: true,
            requireNoteOnFail: true,
          },
        ],
      },
    ],
  },
]

export const audits: Audit[] = [
  {
    id: "a1",
    templateName: "Nadaafadda & Badbaadada Cuntada",
    branchName: "Nomad Coffee — Makka Al-Mukarama",
    auditorName: "Faadumo Cali",
    status: "reviewed",
    score: 93,
    totalItems: 24,
    failedItems: 2,
    startedAt: "2026-08-12T08:10:00Z",
    submittedAt: "2026-08-12T08:52:00Z",
  },
  {
    id: "a2",
    templateName: "Adeegga Macaamiisha",
    branchName: "Banaadir Mart — Bakaaraha",
    auditorName: "Xasan Cabdi",
    status: "submitted",
    score: 81,
    totalItems: 16,
    failedItems: 3,
    startedAt: "2026-08-11T14:00:00Z",
    submittedAt: "2026-08-11T14:35:00Z",
  },
  {
    id: "a3",
    templateName: "Badbaadada Caafimaad (Farmashiye)",
    branchName: "Shifo Pharmacy — Hodan",
    auditorName: "Caasho Maxamed",
    status: "reviewed",
    score: 97,
    totalItems: 20,
    failedItems: 1,
    startedAt: "2026-08-14T09:20:00Z",
    submittedAt: "2026-08-14T09:58:00Z",
  },
  {
    id: "a4",
    templateName: "Nadaafadda & Badbaadada Cuntada",
    branchName: "Xamar Bakery — Wadajir",
    auditorName: "Cabdiraxmaan Nuur",
    status: "in_progress",
    score: null,
    totalItems: 24,
    failedItems: 0,
    startedAt: "2026-08-18T07:45:00Z",
    submittedAt: null,
  },
  {
    id: "a5",
    templateName: "Adeegga Macaamiisha",
    branchName: "Nomad Coffee — Taleex",
    auditorName: "Yuusuf Warsame",
    status: "submitted",
    score: 88,
    totalItems: 16,
    failedItems: 2,
    startedAt: "2026-08-09T11:00:00Z",
    submittedAt: "2026-08-09T11:28:00Z",
  },
]

export const correctiveActions: CorrectiveAction[] = [
  {
    id: "ca1",
    auditId: "a2",
    branchName: "Banaadir Mart — Bakaaraha",
    questionText: "Sagxadaha iyo miisaska ma nadiif baa?",
    description: "Sagxadda dukaanka waxaa ku yaal wasakh; waa in la nadiifiyo oo la sameeyo jadwal nadaafadeed.",
    assignedTo: "Xasan Cabdi",
    status: "in_progress",
    priority: "high",
    dueDate: "2026-08-20",
    linkedSop: "SOP-011: Nadaafadda Maalinlaha ah",
    linkedTraining: "Tababar: Nadaafadda Goobta",
  },
  {
    id: "ca2",
    auditId: "a1",
    branchName: "Nomad Coffee — Makka Al-Mukarama",
    questionText: "Cuntada ma leedahay taariikh dhicis cad?",
    description: "Qaar ka mid ah alaabta ma laha taariikh dhicis. Ku dheji sumadaha taariikhaha.",
    assignedTo: "Faadumo Cali",
    status: "done",
    priority: "medium",
    dueDate: "2026-08-15",
    linkedSop: "SOP-004: Sumadaynta Cuntada",
  },
  {
    id: "ca3",
    auditId: "a5",
    branchName: "Nomad Coffee — Taleex",
    questionText: "Shaqaalaha ma soo dhaweeyaan macaamiisha 30 sekan gudahood?",
    description: "Shaqaalaha waxay u baahan yihiin tababar ku saabsan soo dhaweynta macaamiisha.",
    assignedTo: "Yuusuf Warsame",
    status: "open",
    priority: "low",
    dueDate: "2026-08-25",
    linkedTraining: "Tababar: Adeegga Macaamiisha",
  },
  {
    id: "ca4",
    auditId: "a5",
    branchName: "Xamar Bakery — Wadajir",
    questionText: "Musqulaha ma leeyihiin saabuun iyo biyo?",
    description: "Musqusha ma lahayn saabuun; waa in la buuxiyo si joogto ah.",
    assignedTo: "Cabdiraxmaan Nuur",
    status: "overdue",
    priority: "high",
    dueDate: "2026-08-10",
    linkedSop: "SOP-009: Agabka Musqusha",
  },
]

export const notifications: AppNotification[] = [
  {
    id: "n1",
    title: "Talaabo sax oo cusub",
    body: "Baaritaanka Banaadir Mart wuxuu abuuray talaabo sax mudnaan sare leh.",
    type: "corrective",
    read: false,
    createdAt: "2026-08-18T06:30:00Z",
  },
  {
    id: "n2",
    title: "Baaritaan la gudbiyay",
    body: "Caasho Maxamed waxay gudbisay baaritaanka Shifo Pharmacy (97%).",
    type: "audit",
    read: false,
    createdAt: "2026-08-14T09:58:00Z",
  },
  {
    id: "n3",
    title: "Talaabo dib u dhacday",
    body: "Talaabada saxidda ee Xamar Bakery way dhacday taariikhda la qorsheeyay.",
    type: "corrective",
    read: true,
    createdAt: "2026-08-11T08:00:00Z",
  },
  {
    id: "n4",
    title: "Tababar la xiriira cillad",
    body: "Tababarka 'Adeegga Macaamiisha' ayaa loo diray Nomad Coffee — Taleex.",
    type: "training",
    read: true,
    createdAt: "2026-08-09T12:00:00Z",
  },
]

/** Aggregated KPI figures for the overview dashboard. */
export const overviewStats = {
  auditsThisMonth: 128,
  avgScore: 88,
  openCorrectiveActions: 17,
  overdueActions: 3,
  activeBranches: 31,
  passRate: 84,
}

/** 8-week score trend used by the overview sparkline/bars. */
export const scoreTrend = [
  { label: "Todo 1", value: 79 },
  { label: "Todo 2", value: 82 },
  { label: "Todo 3", value: 80 },
  { label: "Todo 4", value: 85 },
  { label: "Todo 5", value: 87 },
  { label: "Todo 6", value: 84 },
  { label: "Todo 7", value: 89 },
  { label: "Todo 8", value: 88 },
]
